runtime: python39  

entrypoint: streamlit run app.py --server.port $PORT --server.address 0.0.0.0  

handlers:  # Defines URL handlers
  - url: /.*
    script: auto  # Automatically serves all URLs with your Streamlit app